name: Validar nombre de rama

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  validar-rama:
    runs-on: ubuntu-latest

    steps:
      - name: Validar nombre de rama
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Validando rama: $BRANCH_NAME"

          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|release|refactor)/.+$ ]]; then
            echo "❌ El nombre de la rama '$BRANCH_NAME' es inválido."
            echo "Debe comenzar con: feature/, bugfix/, hotfix/, release/ o /refactor"
            exit 1
          fi
