name: Validate last commit message

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  validate-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate last commit message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%s)
          echo "Last commit message: '$COMMIT_MESSAGE'"

          if [[ ! "$COMMIT_MESSAGE" =~ ^[0-9]{3}\ (feat|fix|test|chore|refactor|docs):\ .+ ]]; then
            echo "❌ Invalid commit message: '$COMMIT_MESSAGE'"
            echo "Commit message must follow this format:"
            echo "NNN (type): message"
            echo "Where:"
            echo "  - NNN is a 3-digit number (e.g. 011)"
            echo "  - type is one of: feat, fix, test, chore, refactor, docs"
            echo "  - message is a description"
            exit 1
          else
            echo "✅ Commit message is valid."
          fi
