name: Validate all commit messages

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  validate-commit-messages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get and validate commit messages
        run: |
          echo "🔍 Getting commit messages..."

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BASE_BRANCH=${{ github.event.pull_request.base.ref }}
            git fetch origin "$BASE_BRANCH"
            COMMITS=$(git log --pretty=%s origin/$BASE_BRANCH..HEAD)
          else
            COMMITS=$(git log --pretty=%s ${{ github.event.before }}..${{ github.sha }})
          fi

          echo "$COMMITS" | while IFS= read -r COMMIT_MESSAGE; do
            echo "➡️ Commit: '$COMMIT_MESSAGE'"

            if [[ "$COMMIT_MESSAGE" =~ ^Merge ]]; then
              echo "ℹ️ Skipping merge commit."
              continue
            fi

            if [[ ! "$COMMIT_MESSAGE" =~ ^[0-9]{3}\ \((feat|fix|test|refactor)\):\ .+ ]]; then
              echo "❌ Invalid commit message: '$COMMIT_MESSAGE'"
              echo "✅ Expected format: 'NNN (type): descriptive message'"
              echo "🔒 Push has been blocked."
              exit 1
            fi
          done

          echo "✅ All commit messages are valid."
