name: Validate branch name

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  validate-branch:
    runs-on: ubuntu-latest

    outputs:
      branch_name: ${{ steps.get_branch.outputs.branch_name }}

    steps:
      - name: Debug event and refs
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.head_ref: ${{ github.head_ref }}"

      - name: Get branch name
        id: get_branch
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "branch_name=${{ github.head_ref }}" >> "$GITHUB_OUTPUT"
          else
            echo "branch_name=${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT"
          fi

      - name: Validate branch name
        run: |
          BRANCH_NAME="${{ steps.get_branch.outputs.branch_name }}"
          echo "Validating branch name: $BRANCH_NAME"
          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|release|refactor)/.+$ ]]; then
            echo "❌ Invalid branch name: '$BRANCH_NAME'"
            echo "Branch name must start with one of the following prefixes: feature/, bugfix/, hotfix/, release/, or refactor/"
            exit 1
          else
            echo "✅ Branch name is valid."
          fi
